In [22]:
import numpy as np

In [ ]:
#Criar Array
array = np.array([23,35,25,14,10])
print(array)
print(type(array))


In [6]:
#Array com tipos definidos
array = np.array([23,35,25,14,10], dtype = np.float64)
print(array)
print(type(array))
array = np.array([23,35,25,14,10], dtype = np.int32)
print(array)
print(type(array))

[23. 35. 25. 14. 10.]
<class 'numpy.ndarray'>
[23 35 25 14 10]
<class 'numpy.ndarray'>


In [8]:
#Converter Tipo primitvo do array
array = np.array([2.3,3.5,2.5,1.4,10.9454], dtype = np.float64)
print(array)
print(type(array))
array = array.astype(np.int32)
print(array)

[ 2.3     3.5     2.5     1.4    10.9454]
<class 'numpy.ndarray'>
[ 2  3  2  1 10]


In [10]:
#matrizes em numpy
array = np.array([[1,2,3],[1,2,3],[1,2,3],])
print(array)

2


In [48]:
#Array com valorez aleatorios
arrayAleatorio = np.random.random((3))
print(arrayAleatorio)
print("\n")
#Matriz com valorez aleatorios
arrayAleatorio = np.random.random((3,3))
print(arrayAleatorio)
print("\n")
#array com valorez aleatorios numa distribuição normal
arrayAleatorio = np.random.randn((3))
print(arrayAleatorio)


[0.12174546 0.97291253 0.05142744]


[[0.37099418 0.13884326 0.21146879]
 [0.55934217 0.1395971  0.94936706]
 [0.82563032 0.36352225 0.94047875]]


[-0.21783811  1.31383579  0.44985524]


In [21]:
#gerar numeros aleatorios com seed
#[0.51182162 0.9504637  0.14415961]
seed = np.random.default_rng(1)
array = seed.random(3)
print(array,'\n')

#gerar Inteiros
array = seed.integers(10, size=(3,4))
print(array,'\n')



[0.51182162 0.9504637  0.14415961] 

[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [28]:
#unique
array = np.array([11,12,13,14,15,11,12,13,14,15])
print(array,'\n')
array = np.unique(array,'\n')
#matriz
array = np.array([[11,12,13],[14,15,11],[12,13,14]])
print(array,'\n')
array = np.unique(array)

print(array)

[11 12 13 14 15 11 12 13 14 15] 

[[11 12 13]
 [14 15 11]
 [12 13 14]] 

[11 12 13 14 15]
